const employees = [
  {
    id: 1,
    employeeId: "EMP001",
    firstName: "John",
    lastName: "Doe",
    fullName: "John Doe",
    email: "john.doe@company.com",
    phone: "+1-234-567-8901",
    dateOfBirth: "1990-05-15",
    gender: "Male",
    department: "Engineering",
    position: "Senior Software Engineer",
    jobTitle: "Senior Software Engineer",
    level: "Senior",
    manager: "Jane Smith",
    managerId: 5,
    salary: 95000,
    currency: "USD",
    employmentType: "Full-time",
    hireDate: "2020-03-15",
    status: "Active",
    location: "New York",
    office: "NY-HQ",
    workMode: "Hybrid",
    skills: ["JavaScript", "React", "Node.js", "Python"],
    avatar: "john-doe.jpg"
  },
  {
    id: 2,
    employeeId: "EMP002",
    firstName: "Sarah",
    lastName: "Johnson",
    fullName: "Sarah Johnson",
    email: "sarah.johnson@company.com",
    phone: "+1-234-567-8902",
    dateOfBirth: "1988-08-22",
    gender: "Female",
    department: "Marketing",
    position: "Marketing Manager",
    jobTitle: "Marketing Manager",
    level: "Manager",
    manager: "Michael Brown",
    managerId: 8,
    salary: 85000,
    currency: "USD",
    employmentType: "Full-time",
    hireDate: "2019-06-01",
    status: "Active",
    location: "Los Angeles",
    office: "LA-West",
    workMode: "Remote",
    skills: ["Digital Marketing", "SEO", "Content Strategy", "Analytics"],
    avatar: "sarah-johnson.jpg"
  },
  {
    id: 3,
    employeeId: "EMP003",
    firstName: "Michael",
    lastName: "Chen",
    fullName: "Michael Chen",
    email: "michael.chen@company.com",
    phone: "+1-234-567-8903",
    dateOfBirth: "1995-12-10",
    gender: "Male",
    department: "Design",
    position: "UI/UX Designer",
    jobTitle: "UI/UX Designer",
    level: "Mid-level",
    manager: "Emma Wilson",
    managerId: 12,
    salary: 72000,
    currency: "USD",
    employmentType: "Full-time",
    hireDate: "2021-09-20",
    status: "Active",
    location: "San Francisco",
    office: "SF-Tech",
    workMode: "On-site",
    skills: ["Figma", "Adobe XD", "Sketch", "Prototyping"],
    avatar: "michael-chen.jpg"
  },
  {
    id: 4,
    employeeId: "EMP004",
    firstName: "Emily",
    lastName: "Rodriguez",
    fullName: "Emily Rodriguez",
    email: "emily.rodriguez@company.com",
    phone: "+1-234-567-8904",
    dateOfBirth: "1992-03-18",
    gender: "Female",
    department: "Sales",
    position: "Sales Representative",
    jobTitle: "Sales Representative",
    level: "Junior",
    manager: "David Lee",
    managerId: 15,
    salary: 55000,
    currency: "USD",
    employmentType: "Full-time",
    hireDate: "2022-01-10",
    status: "Active",
    location: "Chicago",
    office: "CHI-Central",
    workMode: "Hybrid",
    skills: ["Salesforce", "Negotiation", "CRM", "Communication"],
    avatar: "emily-rodriguez.jpg"
  },
  {
    id: 5,
    employeeId: "EMP005",
    firstName: "James",
    lastName: "Taylor",
    fullName: "James Taylor",
    email: "james.taylor@company.com",
    phone: "+1-234-567-8905",
    dateOfBirth: "1985-07-25",
    gender: "Male",
    department: "Human Resources",
    position: "HR Director",
    jobTitle: "HR Director",
    level: "Director",
    manager: "CEO",
    managerId: null,
    salary: 110000,
    currency: "USD",
    employmentType: "Full-time",
    hireDate: "2018-02-01",
    status: "Active",
    location: "New York",
    office: "NY-HQ",
    workMode: "On-site",
    skills: ["Recruitment", "Employee Relations", "Compliance", "Leadership"],
    avatar: "james-taylor.jpg"
  },
  {
    id: 6,
    employeeId: "EMP006",
    firstName: "Lisa",
    lastName: "Anderson",
    fullName: "Lisa Anderson",
    email: "lisa.anderson@company.com",
    phone: "+1-234-567-8906",
    dateOfBirth: "1993-11-05",
    gender: "Female",
    department: "Finance",
    position: "Financial Analyst",
    jobTitle: "Financial Analyst",
    level: "Mid-level",
    manager: "Robert King",
    managerId: 20,
    salary: 68000,
    currency: "USD",
    employmentType: "Contract",
    hireDate: "2021-04-15",
    status: "Active",
    location: "Boston",
    office: "BOS-Financial",
    workMode: "Hybrid",
    skills: ["Excel", "Financial Modeling", "SQL", "Tableau"],
    avatar: "lisa-anderson.jpg"
  },
  {
    id: 7,
    employeeId: "EMP007",
    firstName: "David",
    lastName: "Martinez",
    fullName: "David Martinez",
    email: "david.martinez@company.com",
    phone: "+1-234-567-8907",
    dateOfBirth: "1991-09-30",
    gender: "Male",
    department: "IT",
    position: "DevOps Engineer",
    jobTitle: "DevOps Engineer",
    level: "Senior",
    manager: "Jane Smith",
    managerId: 5,
    salary: 92000,
    currency: "USD",
    employmentType: "Full-time",
    hireDate: "2020-08-01",
    status: "On Leave",
    location: "Seattle",
    office: "SEA-Tech",
    workMode: "Remote",
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    avatar: "david-martinez.jpg"
  },
  {
    id: 8,
    employeeId: "EMP008",
    firstName: "Amanda",
    lastName: "White",
    fullName: "Amanda White",
    email: "amanda.white@company.com",
    phone: "+1-234-567-8908",
    dateOfBirth: "1989-04-12",
    gender: "Female",
    department: "Customer Support",
    position: "Support Team Lead",
    jobTitle: "Support Team Lead",
    level: "Lead",
    manager: "Christopher Green",
    managerId: 25,
    salary: 62000,
    currency: "USD",
    employmentType: "Full-time",
    hireDate: "2019-11-20",
    status: "Active",
    location: "Austin",
    office: "AUS-Support",
    workMode: "Remote",
    skills: ["Customer Service", "Zendesk", "Team Management", "Communication"],
    avatar: "amanda-white.jpg"
  }
];

export default employees